# mg-readfiltering CI Docker setup
image: continuumio/miniconda3:latest

stages:
  - test

before_script:
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda config --add channels etetoolkit
    - conda install -q snakemake r-base r-ggplot2 r-scales

test_job:
  stage: test
  script:
    - python3 gen_conf.py ./
    - snakemake --use-conda -p --cores 1 --resources high_diskio=1
