# mg-readfiltering CI Docker setup
image: continuumio/miniconda3:latest

stages:
  - test

before_script:
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda config --add channels etetoolkit
    - conda install -q snakemake r-base r-ggplot2 r-scales

test_job:
  stage: test
  script:
    - mkdir data/
    - echo -e "@BIOMICS-HISEQLN:351:HTLW5BCXX:1:1101:1171:2229 1:N:0:TAAGGCGAAGAGTAGA\nGCCCACGCGGAAAGGCTTTGGTCCGAGCACGCGCAGAAACGTCTCCGGAGCCATGGTGCCTGCGCCTACTTCCACGTCGTACGGCTGCTGCAGAACGCACCCTCGCTCCGCCCAGAATTCCTGCAGGCGAAACAACAATTCCTGAAACGTGAGCGCTGATTTTGATTGAGGAGACGCTACGGGTGTCAAAGCCACAATATCTTCATCTCTTTCACTGGGAACTGAAGCGATTCTAGCAGCCATTCGCTCCCCTTCC\n+\nDDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIICIIIIIIHIIHIIIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIGHIIIHIIIIEHIIIHIIIIIIIIIIIIGIIEHHFIIIIIIIHHHHEHHFHHHHIIIIIIHIHIIHHHHHIGIIIIIEEHHIGICHIIIFBHHHHIHHAHHHHIIIHIIIIIGGHHIIIHIFHII?EFEGHCFHEHIHDFHHFIEHHIGIG-FGFCEHH?HFHIC" | gzip -c > data/mg_forward_paired.fq.gz
    - echo -e "@BIOMICS-HISEQLN:351:HTLW5BCXX:1:1101:1171:2229 2:N:0:TAAGGCGAAGAGTAGA\nCACCATAGCTGGTCGATAAGCAGCGCCAGCCAGCCCGCTGCTTGCATAATCCAGAACGCTCGCAGCCGTCCCCGGGCGGGAATGGCGTTCTGTGCAAAAGTTACGATCAGGGCAGCAAGCATAAGCGCCAGCGCAAAATCACTGACGGTTGTGAGTGCCAGTCCGCG\n+\nDDDDDHIIIIIIIIIIIIIIIIFIIIIHHHGHHHHIIIGIHIIIHIIIIIIIIIIIIIGHIDHIIIEHHHIHHCHHGHHIDHHHGGIIIHIIHIIHCH@GFDHHIHIIIEG?EHHHIIHIIIIGHIIIIHHIIGIIGHIHHIII?GHH@ECHEGH@FHHIHHIIH-?" | gzip -c > data/mg_reverse_paired.fq.gz
    - echo -e "@BIOMICS-HISEQLN:351:HTLW5BCXX:1:1101:1337:2187 1:N:0:TAAGGCGAAGAGTAGA\nCCCATGATCGATGCGCTCGCGCAGGCACGGCAGGCAAAGCCGCCCAGATCAATGGATGTTCCACCCGAAGGAGGGCCCACGCCTGCCTGGGCTGCTGAGGCCATTTGGGGCTGGGCACAGGGTAACCGCGTGCGGCAATTT\n+\nDDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIEHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII" | gzip -c > data/mg_forward_unpaired.fq.gz
    - echo -e "@BIOMICS-HISEQLN:351:HTLW5BCXX:1:1101:5973:2125 2:N:0:TAAGGCGAAGAGTAGA\nGGGCAATCGGAGTTCGGCACGATCGTGCAGTCTACCGCAAGACTTCACCAACTGAAGTAGCTATTCGAGCGTGACCTCGACGGTGCGCTCGTCGCTGCCCCGCACG\n+\nDDDDDHIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIHHHIIIIIIIIIIIIIIIIIIIIIHIHIIIIIIIIGIIHHIIIIIIIIIGIIIIFHIEHHIH" | gzip -c > data/mg_reverse_unpaired.fq.gz
    - python3 gen_conf.py data/
    - snakemake --use-conda -p --cores 1 --resources high_diskio=1 -n
