# mg-readfiltering CI Docker setup
image: continuumio/miniconda3:latest

stages:
  - test

before_script:
    - conda config --add channels conda-forge
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda install -q snakemake r-base gcc 
    - Rscript -e 'install.packages(c("ggplot2", "scales"), repos="http://cran-mirror.cs.uu.nl/")'

test_job:
  stage: test
  script:
    - python3 gen_conf.py ./
    - snakemake --use-conda -p --cores 1 --resources high_diskio=1
