project: mg-preprocess
run-fastqc: false
run-krona: false
run-khist: false
kaiju:
  db: /mnt/zfs/ngs2/ME2/raaijmakers_group/thomg/kaiju_nr
  match-mode: greedy
  max-sub: 2
  min-matchlen: 11
  min-matchscore: 65
  tax-rank: phylum
khmer:
  depth-cutoff: 20
  k-size: 20
  max-gb-ram: 256
